Task 3
rustamscode/product-storage-api pull request #4
Opened 2024-12-29 06:07 UTC by rustamscode

2024-12-30 12:40 UTC, GUR-ok commented
лишние изменения в мре, не относящиейся к задаче

2024-12-30 12:40 UTC, GUR-ok commented
назначь меня ревьюером

2024-12-30 12:40 UTC, GUR-ok commented
название мр поправить на "Task 3: currency conversion"

2024-12-30 13:39 UTC, GUR-ok requested changes

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/advice/CurrencyConverterAdvice.java
> +  final ThreadLocal<BigDecimal> cachedCurrencyRate = new ThreadLocal<>();
Зачем тут тредлокал? есть кэширование на внешнем вызове же?

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/service/CurrencyServiceImpl.java
> +public class CurrencyServiceImpl implements CurrencyService {
CurrencyServiceClientImpl implements CurrencyServiceClient

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/service/CurrencyServiceMock.java
> +public class CurrencyServiceMock implements CurrencyService {
CurrencyServiceClientMock

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/service/CurrencyServiceMock.java
> +
Почему не бин? Где conditional аннотации для активации бина?

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/service/CurrencyService.java
> +public interface CurrencyService {
CurrencyServiceClient. в отедльынй пакет interaction. дто ответа в этот же пакет

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/currency/CurrencyRateProvider.java
> +      currencyRates = currencyService.getCurrencyRateDetails();
если null вернется из второго сервиса?

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/currency/CurrencyRateProvider.java
> +    BigDecimal rate = null;
давай без мутабельных переменных. не нужно инициализировать как нулл, а потом менять значение

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/currency/CurrencyRateProvider.java
> +    BigDecimal rate = null;
return перед switch можно поставить

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/service/CurrencyServiceImpl.java
> +    return webClient
try - catch давай сделаем тут, а не в CurrencyRateProvider. логируй ошибку и возвращай тут null если ошибка. unless = "#result == null не закэширует null. null возвращать не оч хорошая практика, но пометь как nullable возвращаемый тип в сигнатуре метода. код CurrencyRateProvider будет чище. а если мы еще где-то будем дергать этот вызов? там тоже try - catch добавлять как в CurrencyRateProvider?

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/service/dto/CurrencyRateDetails.java
> +@Getter
Почему геттер сеттер? почему не дата или не value?

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/service/dto/CurrencyRateDetails.java
> +@NoArgsConstructor
зачем конструкторы, если есть билдер?

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/filter/CurrencySetterFilter.java
> +    Currency currency;
давай без мутабельных переменных

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/filter/CurrencySetterFilter.java
> +      currency = Currency.fromCurrencyName(request.getHeader("currency"));
что мы тут ловим в исключениях? там либо есть, либо null. обработай через optional

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/filter/CurrencySetterFilter.java
> +      filterChain.doFilter(request, response);
в коде этого метода два раза filterChain.doFilter. этот метод сильно проще без try-catch будет

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/enumeration/Currency.java
> +    throw new UnsupportedCurrencyException(currencyName);
лучше это в else засунуть

2024-12-30 13:39 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/enumeration/Currency.java
> +    throw new UnsupportedCurrencyException(currencyName);
ну и вообще этот метод не нужен. у всех енумов есть valueOf метод из коробки

2024-12-30 13:48 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/advice/CurrencyConverterAdvice.java
> +  final ThreadLocal<BigDecimal> cachedCurrencyRate = new ThreadLocal<>();
Ты тут можешь закэшировать значение из файла, если первый раз из сервиса не получили. и мы в сервис больше не пойдем в этом потоке. А мы должны пытаться из сервиса взять

2024-12-30 13:53 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/service/CurrencyServiceImpl.java
> +  @Cacheable(value = "currencyCache", unless = "#result == null")
unless = "#result == null нетривиальная штука. Где ты это увидел?

2024-12-30 13:58 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/util/DefaultValueLoader.java
> +public class DefaultValueLoader {
Хороший класс. но название не оч. придумай более понятное, чтобы по названию было понятно че делает

2024-12-30 14:00 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/config/CacheConfig.java
> +  @Value("${spring.cache.expiration-time}")
@Value давай не юзать. создавай класс с пропертями конфигов. и его инжекти.

2024-12-30 14:01 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/service/CurrencyServiceImpl.java
> +  @Value("${currency-service.methods.get-currency-rate}")
класс с пропертями нужен

2024-12-30 14:01 UTC, GUR-ok commented on src/main/resources/application.yaml
> +currency-service:
rest:
   currency-service:

2024-12-30 14:02 UTC, GUR-ok commented on src/main/resources/application.yaml
> +currency-service:
Все проперти из раздела rest в класс RestProperties

2024-12-30 14:08 UTC, GUR-ok commented on src/test/java/rustamscode/productstorageapi/service/CurrencyServiceTest.java
> +public class CurrencyServiceTest {
хотелось бы увидеть springboottest на вызов метода find product где в хедере валюту передали RUB и другую

2024-12-30 18:35 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/advice/CurrencyConverterAdvice.java
> +  final ThreadLocal<BigDecimal> cachedCurrencyRate = new ThreadLocal<>();
### **Проблема и решение:** 
При получении листа, а не продукта, каждый элемент листа вызывал метод ` getCurrencyRate()` в методе `processResponse()`. Таким образом метод обращался `CurrencyService `и отправлял запрос для каждого элемента листа. При ошибке от клиентского сервиса приложение продолжало делать retry n * 3 (n - кол-во элементов листа, 3 - кол-во ретраев). Поэтому решил просто сделать такой кеш с ThreadLocal, чтобы каждый поток получал свой актуальный курс и использовал его, неважно работаем мы с 1 элементом или 100 000, обращение идет 1 раз.

### **Вопрос**
Будет ли правильно, если я вместо сохранения в ThreadLocal, заведу отдельный метод для получения CurrencyRate и он будет обращаться к CurrencyService  1 раз в методе `beforeBodyWrite()`. Таким образом, устанавливая значение CurrencyRate для последующего использования?

2024-12-30 18:41 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/service/CurrencyServiceImpl.java
> +public class CurrencyServiceImpl implements CurrencyService {
Исправлено

2024-12-30 18:41 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/service/CurrencyServiceMock.java
> +public class CurrencyServiceMock implements CurrencyService {
Исправлено

2024-12-30 18:50 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/service/CurrencyServiceMock.java
> +
Исправлено

2024-12-30 18:58 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/service/CurrencyService.java
> +public interface CurrencyService {
Исправлено

2024-12-30 19:05 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/currency/CurrencyRateProvider.java
> +    BigDecimal rate = null;
Исправлено

2024-12-30 19:10 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/service/CurrencyServiceImpl.java
> +  @Cacheable(value = "currencyCache", unless = "#result == null")
[stackoverflow](https://stackoverflow.com/questions/12113725/how-do-i-tell-spring-cache-not-to-cache-null-value-in-cacheable-annotation)

> А какой более популярный подход?

2024-12-30 19:12 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/util/DefaultValueLoader.java
> +public class DefaultValueLoader {
Исправлено

2024-12-30 19:27 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/currency/CurrencyRateProvider.java
> +      currencyRates = currencyService.getCurrencyRateDetails();
Исправлено

2024-12-30 19:28 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/service/CurrencyServiceImpl.java
> +    return webClient
Исправлено

2024-12-30 19:51 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/service/dto/CurrencyRateDetails.java
> +@Getter
Во время отладки расставлял, запамятовал.
С `@Value` Jackson не работает, хотя можно [заставить](https://stackoverflow.com/questions/39381474/cant-make-jackson-and-lombok-work-together)
Исправлено

2024-12-30 19:52 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/service/dto/CurrencyRateDetails.java
> +@NoArgsConstructor
Исправлено

2024-12-30 19:53 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/filter/CurrencySetterFilter.java
> +    Currency currency;
Исправлено

2024-12-30 20:05 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/filter/CurrencySetterFilter.java
> +      currency = Currency.fromCurrencyName(request.getHeader("currency"));
Исправлено

2024-12-30 20:05 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/filter/CurrencySetterFilter.java
> +      filterChain.doFilter(request, response);
Исправлено

2024-12-30 20:06 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/enumeration/Currency.java
> +    throw new UnsupportedCurrencyException(currencyName);
Исправлено

2024-12-31 07:41 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/config/CacheConfig.java
> +  @Value("${spring.cache.expiration-time}")
Завел класс для пропертей. 
Исправлено

2024-12-31 07:41 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/service/CurrencyServiceImpl.java
> +  @Value("${currency-service.methods.get-currency-rate}")
Исправлено

2024-12-31 07:41 UTC, rustamscode commented on src/main/resources/application.yaml
> +currency-service:
Исправлено

2024-12-31 10:12 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/advice/CurrencyConverterAdvice.java
> +  final ThreadLocal<BigDecimal> cachedCurrencyRate = new ThreadLocal<>();
Исправлено

2024-12-31 11:16 UTC, rustamscode commented on src/test/java/rustamscode/productstorageapi/service/CurrencyServiceTest.java
> +public class CurrencyServiceTest {
Тест добавлен

2025-01-04 07:19 UTC, GUR-ok requested changes

2025-01-04 07:19 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/advice/CurrencyConverterAdvice.java
> +  Currency currency;
Зачем хранишь currency и currencyRate? Это ж синглтон класс. у него будет одно значение на все запросы

2025-01-04 07:19 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/config/RestProperties.java
> +
пустые строки убрать

2025-01-04 07:19 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/config/RestProperties.java
> +@Configuration
Зачем configuration?

2025-01-04 07:19 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/config/RestProperties.java
> +@Setter
геттер и сеттер заменить на дата. в тестах будет чуть удобней собирать

2025-01-04 07:19 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/config/RestProperties.java
> +    String defaultCurrencyRates;
а тут во вложенных классах будет private? Вообще предпочитают обычные private модификаторы вместо @FieldDefaults(level = AccessLevel.PRIVATE).

2025-01-04 07:19 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/filter/CurrencySetterFilter.java
> +    final Optional<String> currency = Optional.ofNullable(request.getHeader("currency"));
```
        String currency = request.getHeader("currency");
        Optional.ofNullable(currency)
                .map(Currency::valueOf)
                .ifPresent(currencyProvider::setCurrency);

        filterChain.doFilter(request, response);
 ```

2025-01-04 07:19 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/interaction/CurrencyServiceClientImpl.java
> +
пустая строка лишняя

2025-01-04 07:32 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/advice/CurrencyConverterAdvice.java
> +    return methodName.contains("findById") || methodName.contains("findAll") || methodName.contains("search");
- названия методов в константы. 
- Advice сработает на методе findAll в OrderController?

2025-01-04 08:31 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/config/RestProperties.java
> +@Configuration
Не нужен, `@EnableConfigurationProperties(RestProperties.class)` поставил оказывается.
Исправлено

2025-01-04 08:34 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/filter/CurrencySetterFilter.java
> +    final Optional<String> currency = Optional.ofNullable(request.getHeader("currency"));
Исправлено

2025-01-04 08:34 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/config/RestProperties.java
> +
Исправлено

2025-01-04 08:38 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/config/RestProperties.java
> +    String defaultCurrencyRates;
На вложенные классы не распространяется.
Больше не буду использовать **@FieldDefaults**. Путает.
Исправлено

2025-01-04 08:39 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/config/RestProperties.java
> +@Setter
Исправлено

2025-01-04 08:40 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/interaction/CurrencyServiceClientImpl.java
> +
Исправлено

2025-01-04 10:38 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/advice/CurrencyConverterAdvice.java
> +  Currency currency;
Исправлено

2025-01-04 10:39 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/advice/CurrencyConverterAdvice.java
> +    return methodName.contains("findById") || methodName.contains("findAll") || methodName.contains("search");
Методы в константы - исправлено

> Advice сработает на методе findAll в OrderController?
- Нет, его нужно немного изменить - исправил

2025-01-04 16:00 UTC, GUR-ok commented on src/main/java/rustamscode/productstorageapi/advice/CurrencyConverterAdvice.java
> +    BigDecimal currencyRate = currencyRateProvider.getCurrencyRate(currencyProvider.getCurrency());
ты же сохранил в локальную переменную currency. передай ее в .getCurrencyRate(..). + final

2025-01-04 16:00 UTC, GUR-ok approved these changes

2025-01-04 16:07 UTC, rustamscode commented on src/main/java/rustamscode/productstorageapi/advice/CurrencyConverterAdvice.java
> +    BigDecimal currencyRate = currencyRateProvider.getCurrencyRate(currencyProvider.getCurrency());
Исправлено

2025-01-04 16:11 UTC, merged